# Generated by Django 3.2.14 on 2023-02-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_manzana_registroindicemanzana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manzana',
            name='divipola',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
