# Generated by Django 3.2.13 on 2022-07-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punto_Salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(default='', max_length=255)),
                ('municipio', models.CharField(default='', max_length=255)),
                ('direccion', models.CharField(default='', max_length=255, verbose_name='Dirección')),
                ('longitud', models.CharField(default='', max_length=255)),
                ('latitud', models.CharField(default='', max_length=255)),
                ('es_IPS', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='Helvetica', max_length=9, verbose_name='¿Esta sede petenecera o sera una IPS?')),
            ],
        ),
    ]
