# Generated by Django 3.2.13 on 2022-07-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto_salud',
            name='naturaleza_juridica',
            field=models.CharField(choices=[('Pública', 'Pública'), ('Privada', 'Privada'), ('Mixta', 'Mixta')], default='-', max_length=7, verbose_name='Naturaleza jurídica de la IPS'),
        ),
        migrations.AlterField(
            model_name='punto_salud',
            name='es_IPS',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='-', max_length=2, verbose_name='¿Esta sede pertenecerá o será una IPS?'),
        ),
    ]
