# Generated by Django 3.2.14 on 2022-11-02 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='indicador',
            options={'ordering': ['dimension', 'nombre'], 'verbose_name': 'Indicador', 'verbose_name_plural': 'Indicadores'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['departamento', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='registroindicemunicipal',
            options={'ordering': ['indicador', 'municipio'], 'verbose_name': 'Registro índice - Municipal', 'verbose_name_plural': 'Registros índices - Municipal'},
        ),
        migrations.CreateModel(
            name='RegistroIndiceDepartamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.departamento')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.indicador')),
            ],
            options={
                'verbose_name': 'Registro índice - Departamental',
                'verbose_name_plural': 'Registros índices - Departamental',
                'ordering': ['indicador', 'departamento'],
            },
        ),
    ]
