# Generated by Django 3.2.14 on 2022-08-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220722_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divipola', models.CharField(max_length=2)),
                ('nombre', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='punto_salud',
            name='entidad_territorial',
            field=models.CharField(choices=[('Municipal', 'Municipal'), ('Departamental', 'Departamental')], default='-', max_length=13, verbose_name='Entidad territorial a la que pertenece'),
        ),
        migrations.AddField(
            model_name='punto_salud',
            name='nivel_atencion',
            field=models.CharField(choices=[('Primer nivel', 'Primer nivel'), ('Segundo nivel', 'Segundo nivel'), ('Tercer nivel', 'Tercer nivel')], default='-', max_length=13, verbose_name='Nivel de atención (Si es pública)'),
        ),
        migrations.AddField(
            model_name='punto_salud',
            name='tipo_servicios',
            field=models.CharField(choices=[('Primario', 'Primario'), ('Complementario', 'Complementario')], default='-', max_length=14, verbose_name='Tipo de servicios'),
        ),
    ]
