# Generated by Django 3.2.14 on 2022-08-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220810_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='divipola',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
