# Generated by Django 3.2.14 on 2022-08-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220818_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimension',
            options={'verbose_name': 'Dimensión', 'verbose_name_plural': 'Dimensiones'},
        ),
    ]
