# Generated by Django 3.2.14 on 2022-08-25 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_dimension_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punto_salud',
            options={'verbose_name': 'Punto de salud', 'verbose_name_plural': 'Puntos de salud'},
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.indicador')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.municipio')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
